### PR TITLE
Basic Carousel on Quicklook and Product Details

### PR DESCRIPTION
**Pull request by Kiktamo**
Marking this a draft since it technically has the minimum for the Trello card due to only mentioning the Product Detail page(s). 

As it stands it will convert the main image section of any product with extra images into a carousel of images in both the quicklook modal and the product detail page. The images can be scrolled through and will wrap back around when either end is reached. I might see about the product list page as well but carousels seem a bit more complex with more than one on a page as they use variables to keep track of their positioning.

I tried to reduce some redundancy with the product detail page but it's a bit harder than when using templates, so I might use some time to convert the detail page to a template than our current implementation as well.

### CODE REVIEW

**Comment by joelcannon** [comment]
Matt, looks good.  Here is my cosmetic feedback.
It was not obvious which products have more than one image because your carousel controllers are small.  But once I added a break, I noticed them.  I also expected the right arrow to always slide right, but when it goes from the last to the first, it reverses direction.  I would suggest you organize them in a loop, so they can go from 3->1.
A different UI for the controls is to use a row of dots below the image, and each dot jumps to another image and the dot highlights when it is the current image.  You can also have the carousel auto advance on page load, but stop when you click.
This is good enough, but it was not obvious.  Amazon also has a solution.

I don't recommend adding them to the product list page - too complicated/noisy.  The product page is good enough.

No need to refactor much code since this project is almost finished.

Let me know when you are done, and how to test.

**Comment by Kiktamo** [comment]
Alright, I ended up changing the transition to a fade in and out effect as no matter how I tried to loop it I couldn't get a seamless effect just with how it's set up, I added some dot selectors to the carousels, changed the buttons to icons and hopefully increased visibility. Check it out and let me know what you think.

**Review by joelcannon — APPROVED** [review]
works.

**Comment by joelcannon** [comment]
tested, works as main.

**Pull request merged**
